# .goreleaser.yml
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
builds:
  - id: forwarding-svc
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    main: ./cmd/forwarding-svc/main.go
    binary: forwarding-svc
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - 'forwarding-svc:{{ .Env.BRANCH_NAME }}-{{ .Env.BUILD_NUMBER }}'
      - 'forwarding-svc:{{ .Tag }}'
      - 'forwarding-svc:v{{ .Major }}.{{ .Minor }}'
      - 'forwarding-svc:latest'
    skip_push: true
    dockerfile: Dockerfile
    binaries:
      - forwarding-svc
    extra_files:
      - html/
archives:
  -
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - Dockerfile
      - README.md
      - html/**/*
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
env_files:
  github_token: .config/goreleaser/github_token
github_urls:
  api: https://github.secureserver.net/api/v3/
  upload: https://github.secureserver.net/api/uploads/
  download: https://github.secureserver.net/
  # set to true if you use a self-signed certificate
  skip_tls_verify: false
